name: CI

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
  schedule:
    - cron: 0 */12 * * *

jobs:
  template:
    runs-on: [self-hosted, linux, x64]
    needs:
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        uses: ./.github/actions/build
        with:
          docker_arm_host: ${{ secrets.DOCKER_ARM_HOST }}
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
          dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}
          emacs:
