---
image: docker:stable

services:
  - docker:dind

stages:
  - dev
  - std

variables:
  DOCKER_PLATFORMS: linux/amd64,linux/386,linux/arm/v7,linux/arm64/v8
  DOCKER_BUILDX_VERSION: 0.4.1

before_script:
  - apk add --no-cache bash
  - export PATH="$(pwd)/bin:$PATH"
  - source environment

template:
  stage: {{STAGE}}
  script: retry build "{{DIRECTORY}}" "{{TAGS}}"
  resource_group: {{RESOURCE_GROUP}}
  needs: {{NEEDS}}
